name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name : docker login
      env: 
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      run: |
        docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_TOKEN
    - name: Build the Docker image
      run: |
       d=$(date +%Y-%m-%d--%H-%M-%S)
       tag=$d
       echo $GITHUB_SHA
       echo $GITHUB_ENV
       echo $(date +%Y-%m-%d_%H-%M-%S) > tagdate.txt
       cat tagdate.txt
       cat $GITHUB_ENV
       
       docker build . --file Dockerfile --tag ayhans/docker-image-apache2-alpine-01:latest
    - name: Push the Docker image
      run: |
        cat tagdate.txt
        docker push ayhans/docker-image-apache2-alpine-01:$(date +%Y-%m-%d_%H-%M-%S)

